on:
  pull_request:
  push:
    branches: [main]
  schedule:
    - cron: '30 8 * * *'

permissions:
  contents: write

jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v5
      with:
        python-version: 3.x
        enable-cache: true
    - run: make
    - run: make push
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
