---
name: deploy
on:
  pull_request:
  push:
    branches: [main]
  schedule:
    - cron: 30 8 * * *

jobs:
  build:
    name: pr
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
      - run: pip install virtualenv
      - run: make
      - run: make push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
